openapi: 3.0.2
info:
  title: Claim Registration API
  version: 1.1.0
paths:
  /register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Claim'
            examples:
              Example Claim:
                value:
                  insuranceId: INS-123
                  timestamp: '2018-02-10T09:30Z'
                  description: Some claim
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
              examples:
                Some Registration:
                  value:
                    claimId: CLAIM-123
          description: Returned if claim has been successfully registered
      operationId: register
      summary: Register insurance claim
  /claim:
    get:
      parameters:
        -
          examples:
            Example Claim Id:
              value: CLAIM-123
          name: claimId
          description: Id of a claim
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
              examples:
                Example Claim:
                  value:
                    insuranceId: INS-123
                    timestamp: '2018-02-10T09:30Z'
                    description: Some claim
          description: If Claim with given id is found
        '404':
          description: If no claim for give id is available
      operationId: getClaim
      summary: Get Claim by Id
    parameters:
      -
        examples:
          Example Claim:
            value: CLAIM-123
        name: claimId
        description: ''
        schema:
          type: string
        in: query
        required: true
components:
  schemas:
    Claim:
      description: ''
      required:
        - insuranceId
        - timestamp
        - description
      type: object
      properties:
        insuranceId:
          description: ''
          type: string
        timestamp:
          format: date-time
          description: ''
          type: string
        description:
          description: ''
          type: string
      example:
        insuranceId: INS-123
        timestamp: '2018-02-10T09:30Z'
        description: My car was damaged because of flooding
    Registration:
      description: ''
      required:
        - claimId
      type: object
      properties:
        claimId:
          description: ''
          type: string
      example:
        claimId: CLAIM-123
